name: Formatador Black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar Black
        run: pip install black

      - name: Rodar Black
        run: black --check --verbose .