name: Formatador Black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar o black
        run: pip install black

      - name: Rodar o black
        run: black --check --verbose .